### ISSUE TITLE
Add apostrophe linter config files to the project.

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe-enterprise-testbed#26]
We should add the .eslintrc and .stylelintrc files in here so that devs using this to test aren't distracted by their editor saying something is an error simply due to style. This is especially important in this that's meant to be used for more significant testing.

**Comment by kingsleytorlowei** [comment]
I currently don't get this error. A .eslintrc file is present. Can the .stylelintrc still be added?

**Comment by abea** [comment]
You're right that there is an .eslintrc file, which I added just this past summer. I'd forgotten about this issue. I do still see errors as I look at files, however. I think we can close this out, though.
